name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.17.3'
            otp: '27.1'
          - elixir: '1.16.3'
            otp: '26.2'
          - elixir: '1.15.8'
            otp: '26.2'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile dependencies
      run: mix deps.compile
    
    - name: Compile project
      run: mix compile --warnings-as-errors
    
    - name: Check formatting
      run: mix format --check-formatted
      if: ${{ matrix.elixir == '1.17.3' && matrix.otp == '27.1' }}
    
    - name: Run tests
      run: mix test
    
    - name: Run Dialyzer
      run: mix dialyzer
      if: ${{ matrix.elixir == '1.17.3' && matrix.otp == '27.1' }}
